# version: "3.7"
# services:
#   app:
#     build:
#       args:
#         user: sammy
#         uid: 1000
#       context: ./
#       dockerfile: Dockerfile
#     image: travellist
#     container_name: travellist-app
#     restart: unless-stopped
#     working_dir: /var/www/
#     volumes:
#       - ./:/var/www
#     networks:
#       - travellist

#   db:
#     image: mysql:5.7
#     container_name: travellist-db
#     restart: unless-stopped
#     environment:
#       MYSQL_DATABASE: test
#       MYSQL_ROOT_PASSWORD: password
#       MYSQL_PASSWORD: passwprd
#       MYSQL_USER: admin
#       SERVICE_TAGS: dev
#       SERVICE_NAME: mysql
#     volumes:
#       - ./docker-compose/mysql:/docker-entrypoint-initdb.d
#     networks:
#       - travellist



# networks:
#   travellist:
#     driver: bridge


# version: '3.8'
# services: 
#     main:
#         build: 
#             context: .
#             dockerfile: Dockerfile
#         command: 'php artisan serve --host=0.0.0.0'
#         volumes:
#             - .:/app
#         ports:
#             - 8000:8000
#         # depends_on: 
        #     - db

    # queue:
    #     build: 
    #         context: .
    #         dockerfile: Dockerfile
    #     command: 'php artisan queue:work'
    #     depends_on: 
    #         - db        

    # db:
    #     platform: linux/x86_64
    #     image: mysql:8.0
    #     environment: 
    #         MYSQL_DATABASE: main
    #         MYSQL_USER: admin
    #         MYSQL_ROOT: admin
    #         MYSQL_PASSWORD: admin
    #         MYSQL_ROOT_PASSWORD: root
    #     volumes:
    #         - ./storage/dbdata:/var/lib/mysql
    #     ports:
    #         - 3306:3306